import pandas as pd
configfile: "config/config.yaml"

df = (
    pd.read_csv(config["samples"], sep="\t", dtype={"sample_name": str, "unit_name": str})
    .set_index(["sample_name", "unit_name"], drop=False)
    .sort_index()
)

SAMPLES=df.sample_name.unique()
samples_trim=df.sample_name
unit_trim=df.unit_name

rule all:
    input:
        "results/qc/multiqc_report.html",
        expand("results/counts/featureCounts/{sample}_geneCounts.tab", sample=SAMPLES),
        expand("results/counts/salmon/{sample}_geneCounts.tab", sample=SAMPLES),
        expand("results/paQuant/{sample}_paQuant.tab", sample=SAMPLES),
        expand("results/fusion/arriba/{sample}.tsv", sample=SAMPLES),
        expand("results/variantCalling/vcf_filtered/{sample}.vcf.gz", sample=SAMPLES)









include:"rules/inputFunctions.smk"
include:"rules/RNASeq.smk"
include:"rules/variantCalling.smk"
include:"rules/QC.smk"